version: 2

sources:
  - name: raw
    schema: raw_gz_data
    description: raw tables
    tables:
      - name: sales
        identifier: raw_sales
        description: sales data for greenweez online platform
        columns:
          - name: orders_id
            description: unique id of the order
            tests:
              - unique:
                  arguments:
                    column_name: "orders_id || '-' || pdt_id"
              - not_null
      - name: product
        identifier: raw_product
        description: product list in sale
        columns:
          - name: products_id
            description: unique id of the product
            tests:
              - unique
              - not_null
              
              